// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNywbdSl8GxJdePDrgmTatkbhwGsb6Nuc',
    appId: '1:462581991484:web:7073cd5afa40ac83865b39',
    messagingSenderId: '462581991484',
    projectId: 'collaborative-editor-13d1b',
    authDomain: 'collaborative-editor-13d1b.firebaseapp.com',
    storageBucket: 'collaborative-editor-13d1b.firebasestorage.app',
    measurementId: 'G-RQ15644ED6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUJVatfhN0VTJhNhrXJdXWlfyYzEmNNyo',
    appId: '1:462581991484:android:2e143b8c2358914c865b39',
    messagingSenderId: '462581991484',
    projectId: 'collaborative-editor-13d1b',
    storageBucket: 'collaborative-editor-13d1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmgZvLZ3g_c7fzKtn1ZSYleXr0Jhcf1dM',
    appId: '1:462581991484:ios:f560e926fb5bd9d2865b39',
    messagingSenderId: '462581991484',
    projectId: 'collaborative-editor-13d1b',
    storageBucket: 'collaborative-editor-13d1b.firebasestorage.app',
    iosBundleId: 'com.example.coEdit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmgZvLZ3g_c7fzKtn1ZSYleXr0Jhcf1dM',
    appId: '1:462581991484:ios:f560e926fb5bd9d2865b39',
    messagingSenderId: '462581991484',
    projectId: 'collaborative-editor-13d1b',
    storageBucket: 'collaborative-editor-13d1b.firebasestorage.app',
    iosBundleId: 'com.example.coEdit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNywbdSl8GxJdePDrgmTatkbhwGsb6Nuc',
    appId: '1:462581991484:web:46192761a173de36865b39',
    messagingSenderId: '462581991484',
    projectId: 'collaborative-editor-13d1b',
    authDomain: 'collaborative-editor-13d1b.firebaseapp.com',
    storageBucket: 'collaborative-editor-13d1b.firebasestorage.app',
    measurementId: 'G-EM1MP5V78P',
  );

}